### PR TITLE
Searchboxes fix crash

### PR DESCRIPTION
**Pull request by guitorri**

### CODE REVIEW

**Comment by in3otd** [comment]
thanks for the patch; I tried to understand why this fix works/why it didn't reliably work before, but cannot get it. AFAIU, `x1`, `x2`, `y1`, `y2`, `cx`, `cy` are "initialized" here https://github.com/guitorri/qucs/blob/master/qucs/qucs-lib/symbolwidget.cpp#L423-L424 and by `analyseLine()`  https://github.com/guitorri/qucs/blob/master/qucs/qucs-lib/symbolwidget.cpp#L460 so if the component description in the library is good these variables should contain good values, what am I missing here?

**Comment by guitorri** [comment]
Just found out what you are missing. I was using a user library with components with unexpected components...

I  have a library with `hicumL2V2p31n` devices... which are not mentined at:
https://github.com/guitorri/qucs/blob/master/qucs/qucs-lib/symbolwidget.cpp#L285-L288

Ok, now I noticed that the symbol is not shown for the very same reason...
My library happen to be loaded first and the first entry was the above one. 
I guess adding the missing device is one way of solving (I will try). But still, member variables should be initialized in the constructor... no?

**Comment by in3otd** [comment]
oh, thanks! Yes, I agree the current code is not doing the Right Thing, just I did not understand why it should not work with a proper library. And surely the current code could be more robust against that.

**Comment by guitorri** [comment]
This should be a bit more robust now. 
Anyway, it seems wrong that painter code is duplicate... topic for another issue.

**Comment by in3otd** [comment]
oh, I realize now I forgot to merge all this :grimacing: ...I think GitHub notifications should have a "mark as unread" button, to help avoiding to forget things.
I saw you merged #303 and opened another PR with your fixes, thanks for taking care of this...

**Pull request closed without merging**
